# theme: jekyll-theme-midnight
gem "github-pages", group: :jekyll_plugins
# plugins:
#   - jekyll-remote-theme
# remote_theme: "mmistakes/minimal-mistakes@4.26.2"
remote_theme: "pages-themes/midnight"
# remote_theme: "jeffreytse/jekyll-theme-yat"
title: MPPI-Generic
description: A C++/CUDA templated library for MPPI
